refactor(gateway-framework): decouple auth module from topology types
edgeandnode/gateway pull request #741
Opened 2024-05-13 18:31 UTC by LNSD

This PR decouples the framework's `auth` module from any topology types. Additionally, other minor lint warnings have been fixed.

2024-05-13 18:33 UTC, LNSD commented on graph-gateway/src/client_query.rs
> +        .collect::<Vec<_>>();
This is necessary to keep compatibility with the new decoupled module. It will be simplified once the new `network` module PR is merged.

2024-05-13 18:33 UTC, LNSD commented on graph-gateway/src/client_query.rs
> +    let resolved_deployments_ids = deployments.iter().map(|d| d.id).collect::<Vec<_>>();
Idem

2024-05-13 23:59 UTC, Theodus approved these changes
LGTM

2024-05-13 23:59 UTC, Theodus commented on graph-gateway/src/client_query.rs
> +    let resolved_deployments_ids = deployments.iter().map(|d| d.id).collect::<Vec<_>>();
we should move the log event (above this) down do avoid collecting IDs into a vec twice unnecessarily

2024-05-14 00:23 UTC, Theodus requested changes
Hold up. I just realized that we should simplify this a great deal by only checking:
- requested subgraph id on queries by subgraph id
- requested deployment id on queries by deployment id

So we should never be trying to reason about the any vs all relationship when trying to check sets of deployment or subgraph ids. Otherwise were just asking for users to run into unexpected auth errors.

2024-05-14 08:44 UTC, LNSD commented
> Hold up. I just realized that we should simplify this a great deal by only checking:
> 
> * requested subgraph id on queries by subgraph id
> * requested deployment id on queries by deployment id
> 
> So we should never be trying to reason about the any vs all relationship when trying to check sets of deployment or subgraph ids. Otherwise were just asking for users to run into unexpected auth errors.

This simplification has a flaw. 

Imagine that I want to restrict which subgraphs an API key can query, for example, to only one subgraph; I have to add the `SubgraphID` to the "subgraphs allowlist". But, with the simplification above, one can easily bypass this restriction by querying one of the subgraph's deployments.

And vice versa with the deployments: If I want to restrict which deployments an API key can query, I have to add the DeploymentIDs to the "deployments allowlist." Similarly, one could bypass the restriction by querying any subgraph associated with that deployment.

The solution is not trivial, due to the relationship between subgraphs and deployments.

2024-05-14 08:55 UTC, LNSD commented
To be honest, as we are not aiming to do a release in the following days...

I'd rather merge this as is so we don't overcomplicate this PR. Next, I would merge the `network` module PR and integrate it. And after that, work on this authorization issue, as it may require to do some extra work to understand how the allowlists are populated.

2024-05-14 12:28 UTC, Theodus approved these changes

2024-05-16 11:49 UTC, LNSD commented
I have updated the PR with the updated auth checks:

> Context:
> > A subgraph may be associated with multiple deployments. 
> > A deployment may be associated with multiple subgraphs.
> 
> - If a customer sends a request with a Subgraph ID, if this ID is in the authorized subgraphs set (or the set is empty), this request is AUTHORIZED :white_check_mark:.
> - If a customer sends a request with a Subgraph ID not contained in the non-empty authorized subgraphs set, the request is UNAUTHORIZED and rejected :x:.
> - If a customer sends a request with a Deployment ID and ANY subgraph associated with this deployment is contained in the authorized subgraphs set (or the set is empty), the request is AUTHORIZED :white_check_mark:.
> - If a customer sends a request with a Deployment ID and ALL subgraphs associated with this deployment are NOT contained in the non-empty authorized subgraphs set, the request is UNAUTHORIZED and rejected :x:.

I am waiting for the subgraph studio team to give me some input to move things forward.

2024-05-16 16:37 UTC, LNSD commented
@ IainM22 agreed with the behavior described above. We can proceed and merge this PR.

2024-05-16 16:47 UTC, Theodus approved these changes
LGTM

2024-05-16 16:47 UTC, Theodus commented on graph-gateway/src/subgraph_studio.rs
> +                // Map the fetched 9and deserialized) API key into the gateway framework API key.
```suggestion
                // Map the fetched (and deserialized) API key into the gateway framework API key.
```

2024-05-16 20:16 UTC, merged